---
id: do_not_delete
base_name: do_not_delete
tags:
  - Redmine
  - RedminePlugin
presentation_date: "2023-07-07"
presentation_start_time:
presentation_end_time:
version: 1.2023.07.07.1
licenses:
  - X11 License
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1368
height: 768
source_code_uri:
author:
  markup_language: :markdown
  name: Yuya.Nishida.
  email: yuyaAT@ATj96DOT.DOTorg
  rubygems_user: nishidayuya
  slideshare_user: nishidayuya
  speaker_deck_user: nishidayuya
