---
id: nishidayuya-do_not_delete
base_name: do_not_delete
tags: []
presentation_date:
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 800
height: 600
source_code_uri:
author:
  markup_language: :markdown
  name: Yuya.Nishida.
  email: yuyaAT@ATj96DOT.DOTorg
  rubygems_user: nishidayuya
  slideshare_user: nishidayuya
  speaker_deck_user: nishidayuya
